version: '3.8'
services:
  app1:
    image: shraddha:day12v1
    build: . #loc of dockerfile
    container_name: shraddhaday12c1 #optional
    ports:
      - "9981:80"
    networks:
      - shraddhabr111 #want ot use this , but not present as of now
    volumes:
      - shraddhavol12:/mnt/google

networks:
  shraddhabr111: #will create a new docker network

volumes:
  shraddhavol12: 
